# Generated by Django 2.2.1 on 2019-09-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190525_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), help_text='A slug is a short label, used in URLs'),
        ),
    ]
