# Generated by Django 2.2.1 on 2019-09-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190910_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(help_text='A slug is a short label, used in URLs', null=True),
        ),
    ]
