# Generated by Django 2.2.6 on 2019-11-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191020_1551'),
        ('orders', '0004_auto_20191029_2220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederBook',
            new_name='OrderBook',
        ),
    ]
